// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbVTgjYqZ45dtF-JJrYlKgRCp-EtoUy6c',
    appId: '1:647486372820:web:99e41d7fd73d0313603441',
    messagingSenderId: '647486372820',
    projectId: 'test-8a935',
    authDomain: 'test-8a935.firebaseapp.com',
    storageBucket: 'test-8a935.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJq1nHItioIFNct-U_k9IBquh20dMVpvo',
    appId: '1:647486372820:android:9c4b8981c172d802603441',
    messagingSenderId: '647486372820',
    projectId: 'test-8a935',
    storageBucket: 'test-8a935.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmXPZK7bXkgfgqFzg0rJPzwck9fJvYHNA',
    appId: '1:647486372820:ios:a6059061b340620d603441',
    messagingSenderId: '647486372820',
    projectId: 'test-8a935',
    storageBucket: 'test-8a935.appspot.com',
    iosClientId: '647486372820-p9g12qcld9ds5ea5enjqqougmg3dae2o.apps.googleusercontent.com',
    iosBundleId: 'com.example.codebrew2024',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmXPZK7bXkgfgqFzg0rJPzwck9fJvYHNA',
    appId: '1:647486372820:ios:e400de6bd6e99b2f603441',
    messagingSenderId: '647486372820',
    projectId: 'test-8a935',
    storageBucket: 'test-8a935.appspot.com',
    iosClientId: '647486372820-hk845v4bmg00smfabh86nc86vatcb8o2.apps.googleusercontent.com',
    iosBundleId: 'com.example.codebrew2024.RunnerTests',
  );
}
